name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Firebase Config
        env:
          CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          sed -i "s|__FIREBASE_CONFIG_PLACEHOLDER__|$CONFIG|g" index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Pasta onde está o index.html (raiz do projeto)
          branch: gh-pages
